export const models = [
  {
    value: 'sd1',
    label: 'Stable Diffusion V1.5',
  },
  {
    value: 'sd2',
    label: 'Stable Diffusion V2.0',
  },
  {
    value: 'sdxl',
    label: 'Stable Diffusion XL',
  },
];

export const filters = [
  {
    id: 'v1-5-pruned',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'None',
    img: '',
  },
  {
    id: 'sdxl_vaefix_1.0',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'None',
    img: '',
  },
  {
    id: 'sdxl-1',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'DreamShaper XL',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-1.png',
  },
  {
    id: 'sdxl-2',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'RMSDXL - Hybrid Turbo XL',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-2.jpeg',
  },
  {
    id: 'sdxl-3',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'Vibrant Horizon - Turbo XL',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-3.jpeg',
  },
  {
    id: 'sdxl-4',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'WildCardX-XL TURBO',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-4.jpeg',
  },
  {
    id: 'sdxl-5',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'MBBXL Ultimate',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-5.jpeg',
  },
  {
    id: 'sdxl-6',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'Mysterious V4.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-6.jpeg',
  },
  {
    id: 'sdxl-7',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'Copax Cute XL - SDXL1.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-7.jpeg',
  },
  {
    id: 'sdxl-8',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'Niji SE',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-8.jpeg',
  },
  {
    id: 'sdxl-9',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'ProtoVision',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-9.jpeg',
  },
  {
    id: 'sdxl-10',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'DucHaiten V1.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-10.jpeg',
  },
  {
    id: 'sdxl-11',
    category: 'sdxl',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'sdxl_vae.safetensors',
    name: 'Counterfeit V1.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sdxl-11.jpeg',
  },
  // {
  //   id: 'sdxl-lora-1',
  //   category: 'sdxl',
  //   baseModel: 'sdxl_base_1.0',
  //   type: 'safetensors',
  //   modelType: 'lora',
  //   vae: 'sdxl_vae.safetensors',
  //   trigger: '<lora:csal_scenery:1>',
  //   name: 'Pixel Art',
  //   img: 'https://storage.googleapis.com/imagineo-ai/assets/image/filter/sdxl/sdxl-lora-1.jpeg',
  // },
  {
    id: 'sdxl-prompt-1',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      "Broken Glass effect, no background, stunning, something that even doesn't exist, mythical being, energy, molecular, textures, iridescent and luminescent scales, breathtaking beauty, pure perfection, divine presence, unforgettable, impressive, breathtaking beauty, Volumetric light, auras, rays, vivid colors reflects",
    name: 'Vibrant Glass',
    img: 'https://storage.googleapis.com/pai-marketing/filters/vibrant_glass.png',
  },
  {
    id: 'sdxl-prompt-2',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'sticker, 2d cute, fantasy, dreamy, vector illustration, 2d flat, centered, by Tim Burton, professional, sleek, modern, minimalist, graphic, line art, vector graphics',
    name: 'Bella Dreamy Stickers',
    img: 'https://storage.googleapis.com/pai-marketing/filters/dreamy_stickers.png',
  },
  {
    id: 'sdxl-prompt-3',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'ultra hd, realistic, vivid colors, highly detailed, UHD drawing, pen and ink, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light',
    name: 'Ultra Lighting',
    img: 'https://storage.googleapis.com/pai-marketing/filters/ultra_lighting.png',
  },
  {
    id: 'sdxl-prompt-4',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'Watercolor, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski',
    name: 'Watercolor',
    img: 'https://storage.googleapis.com/pai-marketing/filters/watercolor.png',
  },
  {
    id: 'sdxl-prompt-5',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'Miki Asai Macro photography, close-up, hyper detailed, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski',
    name: 'Macro Realism',
    img: 'https://storage.googleapis.com/pai-marketing/filters/macro_realism.png',
  },
  {
    id: 'sdxl-prompt-6',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt: 'trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski',
    name: 'Delicate detail',
    img: 'https://storage.googleapis.com/pai-marketing/filters/delicate_detail.png',
  },
  {
    id: 'sdxl-prompt-7',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'centered, symmetry, painted, intricate, volumetric lighting, beautiful, rich deep colors masterpiece, sharp focus, ultra detailed, in the style of dan mumford and marc simonetti, astrophotography',
    name: 'Radiant symmetry',
    img: 'https://storage.googleapis.com/pai-marketing/filters/radiant_symmetry.png',
  },
  {
    id: 'sdxl-prompt-8',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'unreal engine, greg rutkowski, loish, rhads, beeple, makoto shinkai and lois van baarle, ilya kuvshinov, rossdraws, tom bagshaw, alphonse mucha, global illumination, detailed and intricate environment',
    name: 'Lush illumination',
    img: 'https://storage.googleapis.com/pai-marketing/filters/lush_illumination.png',
  },
  {
    id: 'sdxl-prompt-9',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'outer space, vanishing point, super highway, high speed, digital render, digital painting, beeple, noah bradley, cyril roland, ross tran, trending on artstation',
    name: 'Saturated Space',
    img: 'https://storage.googleapis.com/pai-marketing/filters/saturated_space.png',
  },
  {
    id: 'sdxl-prompt-10',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'neon ambiance, abstract black oil, gear mecha, detailed acrylic, grunge, intricate complexity, rendered in unreal engine, photorealistic',
    name: 'Neon Mecha',
    img: 'https://storage.googleapis.com/pai-marketing/filters/neon_mecha.png',
  },
  {
    id: 'sdxl-prompt-11',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'low poly, isometric art, 3d art, high detail, artstation, concept art, behance, ray tracing, smooth, sharp focus, ethereal lighting',
    name: 'Ethereal Low poly',
    img: 'https://storage.googleapis.com/pai-marketing/filters/ethereal_low_poly.png',
  },
  {
    id: 'sdxl-prompt-12',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'golden ratio, fake detail, trending pixiv fanbox, acrylic palette knife, style of makoto shinkai studio ghibli genshin impact james gilleard greg rutkowski chiho aoshima',
    name: 'Warm box',
    img: 'https://storage.googleapis.com/pai-marketing/filters/warm_box.png',
  },
  {
    id: 'sdxl-prompt-13',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger',
    name: 'Cinematic',
    img: 'https://storage.googleapis.com/pai-marketing/filters/cinematic.png',
  },
  {
    id: 'sdxl-prompt-14',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'sharp focus, emitting diodes, smoke, artillery, sparks, racks, system unit, motherboard, by pascal blanche rutkowski repin artstation hyperrealism painting concept art of detailed character design matte painting, 4 k resolution blade runner',
    name: 'Cinematic (warm)',
    img: 'https://storage.googleapis.com/pai-marketing/filters/cinematic_warm.png',
  },
  {
    id: 'sdxl-prompt-15',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'isometric, digital art, smog, pollution, toxic waste, chimneys and railroads, 3 d render, octane render, volumetrics, by greg rutkowski',
    name: 'Wasteland',
    img: 'https://storage.googleapis.com/pai-marketing/filters/wasteland.png',
  },
  {
    id: 'sdxl-prompt-16',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'acrylic painting, trending on pixiv fanbox, palette knife and brush strokes, style of makoto shinkai jamie wyeth james gilleard edward hopper greg rutkowski studio ghibli genshin impact',
    name: 'Flat palette',
    img: '	https://storage.googleapis.com/pai-marketing/filters/flat_palette.png',
  },
  {
    id: 'sdxl-prompt-17',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      ' professional ominous concept art, by artgerm and greg rutkowski, an intricate, elegant, highly detailed digital painting, concept art, smooth, sharp focus, illustration, in the style of simon stalenhag, wayne barlowe, and igor kieryluk.',
    name: 'Ominous escape',
    img: 'https://storage.googleapis.com/pai-marketing/filters/ominous_escape.png',
  },
  {
    id: 'sdxl-prompt-18',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'cinematic, 4k, epic Steven Spielberg movie still, sharp focus, emitting diodes, smoke, artillery, sparks, racks, system unit, motherboard, by pascal blanche rutkowski repin artstation hyperrealism painting concept art of detailed character design matte painting, 4 k resolution blade runner',
    name: 'Spielberg',
    img: 'https://storage.googleapis.com/pai-marketing/filters/spielberg.png',
  },
  {
    id: 'sdxl-prompt-19',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'epic royal background, big royal uncropped crown, royal jewelry, robotic, nature, full shot, symmetrical, Greg Rutkowski, Charlie Bowater, Beeple, Unreal 5, hyperrealistic, dynamic lighting, fantasy art',
    name: 'Royalistic',
    img: 'https://storage.googleapis.com/pai-marketing/filters/royalistic.png',
  },
  {
    id: 'sdxl-prompt-20',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'sf, intricate artwork masterpiece, ominous, matte painting movie poster, golden ratio, trending on cgsociety, intricate, epic, trending on artstation, by artgerm, h. r. giger and beksinski, highly detailed, vibrant, production cinematic character render, ultra high quality model',
    name: 'Masterpiece',
    img: 'https://storage.googleapis.com/pai-marketing/filters/masterpiece.png',
  },
  {
    id: 'sdxl-prompt-21',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'by Jacob Lawrence and Francis picabia, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger',
    name: 'Wall Art',
    img: 'https://storage.googleapis.com/pai-marketing/filters/wall_art.png',
  },
  {
    id: 'sdxl-prompt-22',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'haze, ultra-detailed, film photography, light leaks, Larry Bud Melman, trending on artstation, sharp focus, studio photo, intricate details, highly detailed, by greg rutkowski',
    name: 'Haze',
    img: '	https://storage.googleapis.com/pai-marketing/filters/haze.png',
  },
  {
    id: 'sdxl-prompt-23',
    category: 'sdxl',
    baseModel: 'sdxl_vaefix_1.0',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'sdxl_vae.safetensors',
    prompt:
      'black and white still, digital Art, perfect composition, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic concept art, soft natural volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, oil on canvas, raphael, caravaggio, greg rutkowski, beeple, beksinski, giger',
    name: 'Black and white(3D)',
    img: 'https://storage.googleapis.com/pai-marketing/filters/black_and_white.png',
  },
  {
    id: 'sd1-1',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Deliberate 3.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-1.jpeg',
  },
  {
    id: 'sd1-2',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Dreamshaper 8.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-2.png',
  },
  {
    id: 'sd1-3',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'RPG V5',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-3.jpeg',
  },
  {
    id: 'sd1-4',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Realistic Vision 5.1',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-4.jpeg',
  },
  {
    id: 'sd1-5',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'ReV Animated',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-5.png',
  },
  {
    id: 'sd1-6',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Counterfeit 3.0',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-6.jpeg',
  },
  {
    id: 'sd1-7',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Protogen Photorealism 5.3',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-7.jpeg',
  },
  {
    id: 'sd1-8',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Protogen Anime 2.2',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-8.jpeg',
  },
  {
    id: 'sd1-9',
    category: 'sd1',
    type: 'safetensors',
    modelType: 'checkpoint',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    name: 'Protogen Photorealism 3.4',
    img: 'https://storage.googleapis.com/imagineo-images/asserts/sd1-9.jpeg',
  },
  {
    id: 'sd1-prompt-1',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'geo2099 style',
    name: 'Geometrieva style',
    img: 'https://storage.googleapis.com/pai-marketing/filters/geometrieva.png',
  },
  {
    id: 'sd1-prompt-2',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'colorpop style',
    name: 'Colorpop',
    img: 'https://storage.googleapis.com/pai-marketing/filters/elizaport_style.png',
  },
  {
    id: 'sd1-prompt-3',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'instaport style',
    name: 'Instaport',
    img: 'https://storage.googleapis.com/pai-marketing/filters/instaport_style.png',
  },
  {
    id: 'sd1-prompt-4',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'pltn style, cute big circular reflective eyes, Pixar render, unreal engine cinematic smooth, intricate detail',
    name: 'Playtoon',
    img: 'https://storage.googleapis.com/pai-marketing/filters/pltn-style.png',
  },
  {
    id: 'sd1-prompt-5',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt:
      'polymode style, toy, soft smooth lighting, soft pastel colors, 3d blender render, polycount, modular constructivism, pop surrealism, physically based rendering',
    name: 'Polymode',
    img: '	https://storage.googleapis.com/pai-marketing/filters/polymode-style.png',
  },
  {
    id: 'sd1-prompt-6',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'woolitize, soft smooth lighting, soft pastel colors',
    name: 'Woolitize',
    img: 'https://storage.googleapis.com/pai-marketing/filters/woolitize.jpeg',
  },
  {
    id: 'sd1-prompt-7',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'appicon style, flat icon',
    name: 'App Icons',
    img: 'https://storage.googleapis.com/pai-marketing/filters/appicon-style.jpg',
  },
  {
    id: 'sd1-prompt-8',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'retroanime style',
    name: 'Retro Anime',
    img: 'https://storage.googleapis.com/pai-marketing/filters/retroanime.png',
  },
  {
    id: 'sd1-prompt-9',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'retrofuturism style',
    name: 'Retro Futurism',
    img: 'https://storage.googleapis.com/pai-marketing/filters/retrofuturism.png',
  },
  {
    id: 'sd1-prompt-10',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'origami style, studio lighting, white background, pastel colors',
    name: 'Origami',
    img: 'https://storage.googleapis.com/pai-marketing/filters/origami.png',
  },
  {
    id: 'sd1-prompt-11',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'analog style',
    name: 'Analog Diffusion',
    img: 'https://storage.googleapis.com/pai-marketing/filters/analogdiffusion.png',
  },
  {
    id: 'sd1-prompt-12',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'playdoh style',
    name: 'Playdoh',
    img: 'https://storage.googleapis.com/pai-marketing/filters/playdoh.png',
  },
  {
    id: 'sd1-prompt-13',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'polaroid style',
    name: 'Polaroid',
    img: 'https://storage.googleapis.com/pai-marketing/filters/polaroid.png',
  },
  {
    id: 'sd1-prompt-14',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'lushill style',
    name: 'Dream Haven',
    img: 'https://storage.googleapis.com/pai-marketing/filters/lushill.jpg',
  },
  {
    id: 'sd1-prompt-15',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'prfm style',
    name: 'Perfume',
    img: 'https://storage.googleapis.com/pai-marketing/filters/prfm.png',
  },
  {
    id: 'sd1-prompt-16',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'pixel style',
    name: 'Pixel',
    img: 'https://storage.googleapis.com/pai-marketing/filters/pixel.jpg',
  },
  {
    id: 'sd1-prompt-17',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'foodmade style',
    name: 'Foodmade',
    img: 'https://storage.googleapis.com/pai-marketing/filters/foodmade.png',
  },
  {
    id: 'sd1-prompt-18',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'olpntng style, oil painting, heavy strokes, paint dripping',
    name: 'Oil Painting',
    img: 'https://storage.googleapis.com/pai-marketing/filters/olpntng.png',
  },
  {
    id: 'sd1-prompt-19',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'popart style',
    name: 'Pop Art',
    img: 'https://storage.googleapis.com/pai-marketing/filters/popart.png',
  },
  {
    id: 'sd1-prompt-20',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'voguestyle, fashion magazine cover',
    name: 'Fashion Magazine',
    img: 'https://storage.googleapis.com/pai-marketing/filters/voguestyle.png',
  },
  {
    id: 'sd1-prompt-21',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'blkmndy, black and white, comic style',
    name: 'Dark Comic',
    img: 'https://storage.googleapis.com/pai-marketing/filters/blkmndy.png',
  },
  {
    id: 'sd1-prompt-22',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'mixpnk style',
    name: 'Mixpunk',
    img: 'https://storage.googleapis.com/pai-marketing/filters/mixpnk.png',
  },
  {
    id: 'sd1-prompt-23',
    category: 'sd1',
    baseModel: 'v1-5-pruned',
    type: 'safetensors',
    modelType: 'prompt',
    vae: 'vae-ft-mse-840000-ema-pruned.ckpt',
    prompt: 'strybk, kids story book style, muted colors, watercolor style',
    name: 'Storybook',
    img: 'https://storage.googleapis.com/pai-marketing/filters/strybk.png',
  },
];

export const samplers = [
  {
    value: 'Euler a',
    label: 'Euler a',
  },
  {
    value: 'Euler',
    label: 'Euler',
  },
  {
    value: 'DPM++ 2M Karras',
    label: 'DPM++ 2M Karras',
  },
  {
    value: 'DPM++ SDE Karras',
    label: 'DPM++ SDE Karras',
  },
  {
    value: 'DPM++ 2M SDE Exponential',
    label: 'DPM++ 2M SDE Exponential',
  },
  {
    value: 'DPM++ 2M SDE Karras',
    label: 'DPM++ 2M SDE Karras',
  },

  {
    value: 'LMS',
    label: 'LMS',
  },
  {
    value: 'Heun',
    label: 'Heun',
  },
  {
    value: 'DPM2',
    label: 'DPM2',
  },
  {
    value: 'DPM2 a',
    label: 'DPM2 a',
  },
  {
    value: 'DPM++ 2S a',
    label: 'DPM++ 2S a',
  },
  {
    value: 'DPM++ 2M',
    label: 'DPM++ 2M',
  },
  {
    value: 'DPM++ SDE',
    label: 'DPM++ SDE',
  },
  {
    value: 'DPM++ 2M SDE',
    label: 'DPM++ 2M SDE',
  },
  {
    value: 'DPM++ 2M SDE Heun',
    label: 'DPM++ 2M SDE Heun',
  },
  {
    value: 'DPM++ 2M SDE Heun Karras',
    label: 'DPM++ 2M SDE Heun Karras',
  },
  {
    value: 'DPM++ 2M SDE Heun Exponential',
    label: 'DPM++ 2M SDE Heun Exponential',
  },
  {
    value: 'DPM++ 3M SDE',
    label: 'DPM++ 3M SDE',
  },
  {
    value: 'DPM++ 3M SDE Karras',
    label: 'DPM++ 3M SDE Karras',
  },
  {
    value: 'DPM++ 3M SDE Exponential',
    label: 'DPM++ 3M SDE Exponential',
  },
  {
    value: 'DPM fast',
    label: 'DPM fast',
  },
  {
    value: 'DPM adaptive',
    label: 'DPM adaptive',
  },
  {
    value: 'LMS Karras',
    label: 'LMS Karras',
  },
  {
    value: 'DPM2 Karras',
    label: 'DPM2 Karras',
  },
  {
    value: 'DPM2 a Karras',
    label: 'DPM2 a Karras',
  },
  {
    value: 'DPM++ 2S a Karras',
    label: 'DPM++ 2S a Karras',
  },
];

export const publicCategory = [
  {
    value: 'None',
    label: 'None',
  },
  {
    value: 'Character',
    label: 'Character',
  },
  {
    value: 'Style',
    label: 'Style',
  },
  {
    value: 'Celebrity',
    label: 'Celebrity',
  },
  {
    value: 'Concept',
    label: 'Concept',
  },
  {
    value: 'Clothing',
    label: 'Clothing',
  },
  {
    value: 'Base Model',
    label: 'Base Model',
  },
  {
    value: 'Poses',
    label: 'Poses',
  },
  {
    value: 'Background',
    label: 'Background',
  },
  {
    value: 'Tool',
    label: 'Tool',
  },
  {
    value: 'Buildings',
    label: 'Buildings',
  },
  {
    value: 'Vehicle',
    label: 'Vehicle',
  },
  {
    value: 'Objects',
    label: 'Objects',
  },
  {
    value: 'Animal',
    label: 'Animal',
  },
  {
    value: 'Action',
    label: 'Action',
  },
  {
    value: 'Assets',
    label: 'Assets',
  },
];
